### PR TITLE
Journal club for Dimitri Schmid (DS) and Lola Kourouma (LK) and an additional person

### PR DESCRIPTION
**Pull request by schmiddieth**
Dear Prof. Robinson

Lola and I would like to present the paper: A test metric for assessing single-cell RNA-seq batch correction (https://www.nature.com/articles/s41592-018-0254-1) on the 23rd of November. Therefore I created a pull request. 

Have a great Friday afternoon and best wishes,
Dimitri

### CODE REVIEW

**Comment by markrobinsonuzh** [comment]
Chosen paper looks really good, but one of the previous PRs already took that slot. Would you consider another free date, like 02.11., 26.10., 14.12. ?

**Comment by schmiddieth** [comment]
We would like to do it on dec the 14th then if that is still possible. 

Best wishes,
Dimitri

**Comment by markrobinsonuzh** [comment]
OK, it should still be free. Can you update the PR please?

**Comment by markrobinsonuzh** [comment]
I will close this PR. You can open another one for the time slot on 14.12.

**Pull request closed without merging**
