### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by schmiddieth**

### CODE REVIEW

**Comment by markrobinsonuzh** [comment]
I'm going to close this PR without merging, because you are operating on quite an old fork and this leads to a lot of merge conflicts. Can you put your paper "registration" in a new PR, ideally after updating/creating/putting changes into a new up-to-date fork?

**Comment by schmiddieth** [comment]
Dear Prof. Robinson

I thought I just forked the new materials Repo and added the changes before submitting my new pull request. I don’t know what else to do to get the most recent repo and already tried like 3 times. Can you explain to me again how to do this properly before submitting another pull request?

Thank you very much and have a great Sunday.

Best wishes,
Dimitri Schmid

**Comment by markrobinsonuzh** [comment]
I think the cleanest/easiest way is to delete your fork `schmiddieth/material` (i.e., goto https://github.com/schmiddieth/material, Settings, Danger Zone, "Delete this repository") and then afterwards, re-fork a fresh copy (because then it will be fully up-to-date with the main `sta426hs2020/material` repo). Then, put your changes into the `README.md` of the fresh fork and send a PR from that.

Let me know how it goes.

**Comment by schmiddieth** [comment]
Ok, I did as instructed and it seemed to work. Thank you very much for the update and the how to do it. I was just not sure, if there is an easy browser assisted way to do it, without having to download the whole repo.

Have a nice rest of your Sunday.

Best wishes,
Dimitri

**Pull request closed without merging**
