### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dcevid**
Put ourselves in the Journal Club schedule

### CODE REVIEW

**Comment by markrobinsonuzh** [comment]
Unfortunately, there was a PR about 2 hours before yours that took the 02.11. slot .. would you consider 26.10.?

**Comment by markrobinsonuzh** [comment]
Also, that means you'll need to please update the PR such that there are no conflicts.

**Comment by dcevid** [comment]
Dear Prof Robinson

Thank you very much for your message. 26.10. sounds good to me. Is it ok then to present this paper: https://www.nature.com/articles/s41540-019-0118-z ? I sent a message to the journal_club channel on Slack, but I believe you have not seen it. I would like to present something that is related to causality, pathways and differential expression analysis.

Yours sincerely,
Domagoj Cevid

**Comment by markrobinsonuzh** [comment]
I answered on slack but will answer here too. Paper looks really good. Can you update the PR? Then, I can merge it.

**Review by markrobinsonuzh — APPROVED** [review]

**Pull request merged**
